// AUTO-GENERATED by scripts/process_assets.py — do not hand-edit.
export const IMG = {
  'bg-wood': { src: "./img/bg-wood.jpg", webp: "./img/bg-wood.webp" },
  'bg-metal': { src: "./img/bg-metal.jpg", webp: "./img/bg-metal.webp" },
  'bg-felt': { src: "./img/bg-felt.jpg", webp: "./img/bg-felt.webp" },
  'foil-gold': { src: "./img/foil-gold.jpg", webp: "./img/foil-gold.webp" },
  'foil-rose': { src: "./img/foil-rose.jpg", webp: "./img/foil-rose.webp" },
  'foil-neon': { src: "./img/foil-neon.jpg", webp: "./img/foil-neon.webp" },
  'foil-carbon': { src: "./img/foil-carbon.jpg", webp: "./img/foil-carbon.webp" },
  'card-gems': { src: "./img/card-gems.jpg", webp: "./img/card-gems.webp" },
  'card-fruits': { src: "./img/card-fruits.jpg", webp: "./img/card-fruits.webp" },
  'card-cyber': { src: "./img/card-cyber.jpg", webp: "./img/card-cyber.webp" },
  'card-aztec': { src: "./img/card-aztec.jpg", webp: "./img/card-aztec.webp" },
};
export const ASSET = {
  'ticket': { src: "./assets/ticket.png", webp: "./assets/ticket.webp" },
  'bot-gold': { src: "./assets/bot-gold.png", webp: "./assets/bot-gold.webp" },
  'bot-diamond': { src: "./assets/bot-diamond.png", webp: "./assets/bot-diamond.webp" },
  'coins': { src: "./assets/coins.png", webp: "./assets/coins.webp" },
  'gift': { src: "./assets/gift.png", webp: "./assets/gift.webp" },
  'crown': { src: "./assets/crown.png", webp: "./assets/crown.webp" },
  'logo': { src: "./assets/logo.png", webp: "./assets/logo.webp" },
};
export const ART = {
'appletree': { src: "./art/appletree.jpg", webp: "./art/appletree.webp" },
  'booster': { src: "./art/booster.jpg", webp: "./art/booster.webp" },
  'final': { src: "./art/final.jpg", webp: "./art/final.webp" },
'goldrush': { src: "./art/goldrush.jpg", webp: "./art/goldrush.webp" },
'luckycat': { src: "./art/luckycat.jpg", webp: "./art/luckycat.webp" },
'megajack': { src: "./art/megajack.jpg", webp: "./art/megajack.webp" },
'miniscratch': { src: "./art/miniscratch.jpg", webp: "./art/miniscratch.webp" },
  'mystery': { src: "./art/mystery.jpg", webp: "./art/mystery.webp" },
'quickcash': { src: "./art/quickcash.jpg", webp: "./art/quickcash.webp" },
'sanddollars': { src: "./art/sanddollars.jpg", webp: "./art/sanddollars.webp" },
'seaturtle': { src: "./art/seaturtle.jpg", webp: "./art/seaturtle.webp" },
'snakeeyes': { src: "./art/snakeeyes.jpg", webp: "./art/snakeeyes.webp" },
'twowin': { src: "./art/twowin.jpg", webp: "./art/twowin.webp" },
};

export function pick(a) {          // <picture>-ready source pair
  if (!a) return undefined;
  return a.webp && supportsWebp() ? a.webp : a.src;
}
let _webp;
export function supportsWebp() {
  if (_webp === undefined) {
    try {
      const c = document.createElement('canvas');
      _webp = c.toDataURL('image/webp').indexOf('data:image/webp') === 0;
    } catch { _webp = false; }
  }
  return _webp;
}
